package co.codigoj.webservice.services.catagoriaws.ws;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2020-02-01T01:11:46.120-05:00
 * Generated source version: 3.1.16
 * 
 */
@WebService(targetNamespace = "http://webservice.codigoj.co/services/catagoriaws/ws", name = "catagoriaws")
@XmlSeeAlso({co.codigoj.webservice.entity.ws.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-02-01T01:11:46.120-05:00", comments = "Apache CXF 3.1.16")
public interface Catagoriaws {

    @WebMethod(action = "http://webservice.codigoj.co/services/catagoriaws/ws/buscarDatos")
    @WebResult(name = "buscarResponse", targetNamespace = "http://webservice.codigoj.co/entity/ws/types", partName = "response")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2020-02-01T01:11:46.120-05:00")
    public co.codigoj.webservice.entity.ws.types.BuscarResponse buscarDatos(
        @WebParam(partName = "request", name = "buscarRequest", targetNamespace = "http://webservice.codigoj.co/entity/ws/types")
        co.codigoj.webservice.entity.ws.types.BuscarRequest request
    );
}
